name: Renovate CI

on:
  pull_request:

jobs:
  validate:
    strategy:
      fail-fast: true
      matrix:
        config_file: ["org-inherited-config.json"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Setup Node.js
        uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
        with:
          node-version: latest

      # Hosted Renovate should use the latest available version, so always
      # install the newest version of Renovate
      - name: Install dependencies
        run: npm install -g renovate

      - name: Validate Renovate config
        env:
          CONFIG_FILE: ${{ matrix.config_file }}
        run: renovate-config-validator --strict ${CONFIG_FILE}
