name: Renovate Self-Hosted

on:
  pull_request:
    branches:
      - main
    paths:
      - ".github/workflows/renovate.yml"
      - "org-inherited-config.json"
  schedule:
    # Every 15 minutes from 8:00 to 21:00 UTC
    - cron: "*/15 8-21 * * *"
  workflow_dispatch:

jobs:
  renovate:
    runs-on: ubuntu-latest
    steps:
      - name: Get Token
        id: get-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: ${{ vars.RENOVATE_APP_ID }}
          private-key: ${{ secrets.RENOVATE_PRIVATE_KEY }}
          owner: ${{ github.repository_owner }}

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 1
          token: ${{ steps.get-token.outputs.token }}
          persist-credentials: false

      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v41.0.22
        env:
          RENOVATE_DRY_RUN: ${{ github.event_name == 'pull_request' && 'full' }}
        with:
          token: ${{ steps.get-token.outputs.token }}
          configurationFile: ./renovate-config.json
